### ISSUE TITLE
API 명세서 참고해서 API 작성하기

### ISSUE THREAD

**Issue by krokerdile** [sgdevcamp2023/recycle#154]
연관 에픽: #152 

### Question
https://github.com/sgdevcamp2023/recycle/blob/be/%2349-review-api-mock/be/docs/QUESTION/API.md

### Review
https://github.com/sgdevcamp2023/recycle/blob/be/%2349-review-api-mock/be/docs/REVIEW/API.md

### Member 
https://github.com/sgdevcamp2023/recycle/blob/be/%2354-member-api-mock/be/docs/member/API.md

### Comment
https://github.com/sgdevcamp2023/recycle/blob/be/%2349-review-api-mock/be/docs/COMMENT/API.md

**Comment by belljun3395** [comment]
https://app.swaggerhub.com/apis/jon53/Zzuag/1.0.0
