### ISSUE TITLE
로그인, 회원가입 페이지 와이어프레임

### ISSUE THREAD

**Issue by Klomachenko** [sgdevcamp2023/recycle#31]
연관 에픽 : #28 

## 메인화면

![image](https://github.com/sgdevcamp2023/recycle/assets/102893954/c58ac274-c5e6-456e-8950-40f0bfb00621)

## 회원가입
- 일반
![image](https://github.com/sgdevcamp2023/recycle/assets/102893954/42545ce9-e424-4998-8f0b-90563c8ed9a8)
- 모달
![image](https://github.com/sgdevcamp2023/recycle/assets/102893954/80a8c228-aeb4-4b13-9007-bd13da7fe25d)

## 로그인
- 일반
![image](https://github.com/sgdevcamp2023/recycle/assets/102893954/99de6f70-767a-4081-b573-72d270457a5c)
- 모달 
![image](https://github.com/sgdevcamp2023/recycle/assets/102893954/e5c45ef9-89bc-4d7c-a72b-7c7e57795764)
---

## 반영한 것
최초 종준님께서 '필수 입력란' 말씀하신 부분은 브런치 디자인 가이드북 토대로 '필수' 라는 글자를 첨부하는 것으로 마무리 하였습니다.

추가로 깃허브와, 이메일 입력은 글 옆에 삼각형 기호를 첨부하여, 어떻게 쓰이는지 알 수 있도록 모달을 생성할 예정입니다.

## 피드백 요청
일반 화면과 모달 화면 중 어느 것이 괜찮아 보이는지 말씀해 주세요

**Comment by Klomachenko** [comment]
- 깃허브 아이콘 클릭 (벨로그)
- 이메일 인증 버튼 추가
- 이메일 인증시 버튼 추가로 눌리지 않도록
- 이메일 인증시 아래 인증번호 입력란 추가

**Comment by belljun3395** [comment]
- 이메일과 깃헙 연결의 경우 별도의 창이 필요할 것 같습니다. 화면 구성은 자율이지만 이메일과 깃헙 연결과정이 통일된 느낌이면 좋을 것 같습니다.
- 이메일 인증에서 이메일 인증 요청 버튼을 클릭 하였다는 것을 명시적으로 나타내어주었으면 좋겠습니다.
- 추가로 계속 클릭하는 것을 막는 것을 있으면 좋을 것 같아요

**Comment by Klomachenko** [comment]
- 아이디 비밀번호만 입력받고, 깃헙, 이메일의 경우 소개 페이지를 따로 제작하는 것으로!
