### ISSUE TITLE
도메인 이벤트 목록 정의

### ISSUE THREAD

**Issue by belljun3395** [sgdevcamp2023/recycle#32]

**Comment by belljun3395** [comment]
멤버 
- 멤버 생성 이벤트
- 멤버 업데이트 이벤트
- 멤버 삭제 이벤트
- 로그인, 로그아웃 이벤트

배치
- 알림 목록 이벤트

질문
-  질문 요청 이벤트

**Comment by sso9594** [comment]
리뷰
- 리뷰 수정 이벤트
- 리뷰 삭제 이벤트

**Comment by belljun3395** [comment]
본인이 발행할 이벤트에 어떤 정보가 포함될지 작성

본인이 필요한 이벤트 목록 작성하기
