### ISSUE TITLE
Review API 리스트

### ISSUE THREAD

**Issue by sso9594** [sgdevcamp2023/recycle#49]
연관 에픽 : #20 

# API 리스트

| API 종류 | 메서드 | URI | 설명 |
| --- | --- | --- | --- |
| Posts | POST | /api/posts | 질문 글 생성 |
|  | GET | /api/posts/{post_id} | 질문 글 상세 조회 |
|  | GET | /api/posts/my | 멤버 기준 질문 글 목록 조회 |
|  | GET | /api/posts/my/request | 멤버간 리뷰 요청 질문 글 목록 조회 |
|  | GET | /api/posts/my/search | 멤버 기준 질문 글 목록에서 ‘검색어’를 포함한 내용을 가진 글 리스트 조회 |
|  | PUT | /api/posts/{post_id} | 질문 글 수정 |
|  | DELETE | /api/posts/{post_id} | 질문 글 삭제 |
|  | POST | /api/posts/temp | 질문 글 임시 저장 |
|  | GET | /api/posts/my/temp | 멤버 기준 질문 글 임시 저장 목록 조회 |
|  | GET | /api/posts/my/temp/{UUID} | 질문 글 임시 저장 가져오기 |
|  | GET | /api/posts/{post_id}/reviewers | 질문 글에 리뷰 단 리뷰어 목록 |
| Reviews | POST | /api/posts/{post_id}/reviews | 리뷰 생성 |
|  | GET | /api/posts/{post_id}/reviews/{review_id} | 리뷰 조회 |
|  | GET | /api/reviews/my | 멤버 기준 리뷰 목록 조회 |
|  | GET | /api/posts/{post_id}/reviews | 질문 글 기준 리뷰 목록 조회 |
|  | GET | /api/reviews/my/search | 멤버 기준 리뷰 목록에서 ‘검색어’를 포함한 내용을 가진 글 리스트 조회 |
|  | PUT | /api/posts/{post_id}/reviews/{review_id} | 리뷰 수정 |
|  | DELETE | /api/posts/{post_id}/reviews/{review_id} | 리뷰 삭제 |
|  | POST | /api/posts/{post_id}/reviews/temp | 리뷰 임시저장 |
|  | GET | /api/reviews/my/temp | 멤버 기준 리뷰 임시 저장 목록 조회 |
|  | GET | /api/reviews/my/temp/{UUID} | 리뷰 임시 저장 가져오기 |
| Comments | POST | /api/posts/{post_id}/comments | 댓글 생성 |
|  | GET | /api/posts/{post_id}/comments | 질문 글 기준 댓글 목록 조회 |
|  | PUT | /api/posts/{post_id}/comments/{comment_id} | 댓글 수정 |
|  | DELETE | /api/posts/{post_id}/comments/{comment_id} | 댓글 삭제 |
| Reply | POST | /api/posts/{post_id}/comments/{comment_id}/reply | 대댓글 생성 |
|  | GET | /api/posts/{post_id}/comments/{comment_id}/reply | 댓글 기준 대댓글 목록 조회 |
|  | PUT | /api/posts/{post_id}/comments/{comment_id}/reply/{reply_id} | 대댓글 수정 |
|  | DELETE | /api/posts/{post_id}/comments/{comment_id}/reply/{reply_id} | 대댓글 삭제 |

**Comment by belljun3395** [comment]
# Question API

# API 리스트

| API 종류 | 메서드 | URI | 설명 |
| --- | --- | --- | --- |
| Posts | POST | /api/v1/questions?temp={boolean:false} | 질문 글 생성, 질문 글 임시 저장 |
|  | GET | /api/v1/questions/{question_id} | 질문 글 조회 |
|  | GET | /api/v1/me/questions?temp={boolean:false}&t_id={temp_question_id:nullable} | 멤버의 질문 글 목록 조회, 멤버의 임시 질문 글 목록 조회, 멤버의 임시 질문 글 조회, |
|  | GET | /api/v1/me/requests/reviews | 리뷰 요청 목록 조회 |
|  | GET | /api/v1/questions/search?me={boolean:false}&query={검색내용}&page(통상적으로) | 멤버의 질문 글 목록에서 검색 |
|  | DELETE | /api/v1/questions/{question_id} | 질문 글 삭제 |
|  | GET | /api/v1/me/questions/reviewers?question_id={question_id:nullable} | 질문 글에 리뷰 단 리뷰어 목록 |
| Reviews | POST | /api/v1/quetions/{quetion_id}/reviews?temp={boolean:false} | 리뷰 생성, 리뷰 임시 저장 |
|  | GET | /api/v1/me/reviews | 멤버가 작성한 리뷰 목록 조회 |
|  | GET | /api/v1/quetions/{quetion_id}/reviews?temp={boolean:false}&t_id={temp_question_id:nullable} | 질문 글 기준 리뷰 목록 조회, 질문 글 기준 임시 리뷰 목록 조회 |
|  | GET | /api/v1/reviews/search?me={boolean:false}&query={검색내용}&page(통상적으로) | 멤버가 질문글에 작성한 리뷰 목록에서 검색 |
|  | PUT | /api/v1/quetions/{quetion_id}/reviews/{review_id} | 리뷰 수정 |
|  | DELETE | /api/v1/quetions/{quetion_id}/reviews/{review_id} | 리뷰 삭제 |
| Comments | POST | /api/v1/quetions/{quetion_id}/comments | 댓글 생성 |
|  | GET | /api/v1/quetions/{quetion_id}/comments | 질문 글 기준 댓글 목록 조회 |
|  | PUT | /api/v1/quetions/{quetion_id}/comments/{comment_id} | 댓글 수정 |
|  | DELETE | /api/v1/quetions/{quetion_id}/comments/{comment_id} | 댓글 삭제 |

**Comment by sso9594** [comment]
# API 리스트

| API 종류 | 메서드 | URI | 설명 |
| --- | --- | --- | --- |
| Posts | POST | /api/v1/questions | 질문 글 생성 |
|  | POST | /api/v1/questions/temp | 질문 글 임시 저장 |
|  | GET | /api/v1/questions-query/{question_id} | 질문 글 조회 |
|  | GET | /api/v1/me-query/questions | 멤버의 질문 글 목록 조회 |
|  | GET | /api/v1/me-query/questions/temp?t_id={temp_question_id:nullable} | 멤버의 임시 질문 글 목록 조회, 멤버의 임시 질문 글 조회, |
|  | GET | /api/v1/questions-query/search?me={boolean:false}&query={검색내용}&page={페이지수:nullable}&size={한 페이지에 담을수:nullable} | 멤버의 질문 글 목록에서 검색 |
|  | DELETE | /api/v1/questions/{question_id} | 질문 글 삭제 |
|  | GET | /api/v1/me-query/requests/reviews | 리뷰 요청 목록 조회 |
|  | GET | /api/v1/me-query/questions/reviewers?question_id={question_id:nullable} | 질문 글에 리뷰 단 리뷰어 목록 |
| Reviews | POST | /api/v1/quetions/{quetion_id}/reviews | 리뷰 생성  |
|  |  | /api/v1/quetions/{quetion_id}/reviews/temp | 리뷰 임시 저장 |
|  | GET | /api/v1/me-query/reviews | 멤버가 작성한 리뷰 목록 조회 |
|  | GET | /api/v1/quetions-query/{quetion_id}/reviews | 질문 글 기준 리뷰 목록 조회 |
|  |  | /api/v1/quetions-query/{quetion_id}/reviews/temp?t_id={temp_question_id:nullable} | 질문 글 기준 임시 리뷰 목록 조회 |
|  | GET | /api/v1/reviews-query/search?me={boolean:false}&query={검색내용}&page={페이지수:nullable}&size={한 페이지에 담을수:nullable} | 멤버가 질문글에 작성한 리뷰 목록에서 검색 |
|  | PUT | /api/v1/quetions/{quetion_id}/reviews/{review_id} | 리뷰 수정 |
|  | DELETE | /api/v1/quetions/{quetion_id}/reviews/{review_id} | 리뷰 삭제 |
| Comments | POST | /api/v1/quetions/{quetion_id}/comments | 댓글 생성 |
|  | GET | /api/v1/quetions-query/{quetion_id}/comments | 질문 글 기준 댓글 목록 조회 |
|  | PUT | /api/v1/quetions/{quetion_id}/comments/{comment_id} | 댓글 수정 |
|  | DELETE | /api/v1/quetions/{quetion_id}/comments/{comment_id} | 댓글 삭제 |
