### ISSUE TITLE
1/15 중간공유회 정리

### ISSUE THREAD

**Issue by krokerdile** [sgdevcamp2023/recycle#95]
## 다같이 회고 하기
https://metroretro.io/BO8RCH3S8K1P
### Keep
<img width="761" alt="스크린샷 2024-01-16 오전 10 32 27" src="https://github.com/sgdevcamp2023/recycle/assets/39644976/f31eb904-b977-4cf2-a513-812492cd494c">

### Problems
<img width="761" alt="스크린샷 2024-01-16 오전 10 33 13" src="https://github.com/sgdevcamp2023/recycle/assets/39644976/a514487c-ba67-4c1c-b20c-0241b06ebcb8">

### Try
<img width="720" alt="스크린샷 2024-01-16 오전 10 33 48" src="https://github.com/sgdevcamp2023/recycle/assets/39644976/b0f477e0-3169-44da-9d80-184be9f90608">

## 축제로 시작해서 전쟁이 되버린 중간공유회 발표
![image](https://github.com/sgdevcamp2023/recycle/assets/39644976/25c3711d-5e05-4a9c-a468-f2bf28b28b5e)

**Comment by krokerdile** [comment]
발표 자료는 나중에 위키랑 main 브랜치에 추가해두는 걸로!

**Comment by Klomachenko** [comment]
발표 고생하셨습니다!

**Comment by sso9594** [comment]
발표 고생하셨습니다~
